### ISSUE TITLE
Zjada literke "n"

### ISSUE THREAD

**Issue by anncpl** [regdos/DirectAdmin-Evolution-PL#2]
Zauwazylem bardzo dziwna sytuacje. 
We wszelkich komunikatach w okienkach modalnych (np w komunikacie po zalozeniu maila lub dodaniu nowej domeny) zjada literke "n"
Co ciekawe - duze litery "N" sa wyswietlone poprawnie.

Przyklady:
- lista domen: 
![image](https://user-images.githubusercontent.com/43933601/46583670-be195a00-ca5a-11e8-859a-fc96ec3cebad.png)
- okienko modalne (z brakujacymi "n"): 
![image](https://user-images.githubusercontent.com/43933601/46583680-da1cfb80-ca5a-11e8-8e88-b44b8534378f.png)

Wyglada chyba na jakis (dosc smieszny i ciekawy) bug :-)

Wersja DA najnowsza, wersja tlumaczenia najnowsza, sprawdzane pod wiekszoscia ogolnie znanych przegladarek WWW

**Comment by regdos** [comment]
W aktualnej wersji DA ten problem nie występuje.
