### ISSUE TITLE
System plików

### ISSUE THREAD

**Issue by xBIGDBx** [regdos/DirectAdmin-Evolution-PL#8]
Przy ustawionej wersji językowej PL niestety nie wyświetla się tabela z danymi statystyk zużycia (Informacje o systemie i Pliki -> Pełne statystyki zużycia ->Tabela na samym dole). Przy wersji angielskiej działa to normalnie (dane się wyświetlają)
![evolution_pl](https://user-images.githubusercontent.com/59751956/72195098-18009080-3411-11ea-9762-a24bc4e77c96.PNG)
.

**Comment by regdos** [comment]
Tak się dzieje w każdym innym języku innym niż Angielski. Zgłosiłem im to na forum - https://forum.directadmin.com/threads/empty-stats-for-a-language-other-than-english.60088/

**Comment by xBIGDBx** [comment]
Dzięki, będę śledził temat.

**Comment by regdos** [comment]
Poprawka wejdzie z wersją DA 1.60.0 https://directadmin.com/features.php?id=2633
